version: '3.8'

services:
  web:
    build: .
    hostname: apa.lbs.local
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - APP_DOMAIN=${APP_DOMAIN:-apa.lbs.local}
      - APP_HOST=0.0.0.0
      - APP_PORT=${APP_PORT:-5000}

  report_generator:
    build: .
    volumes:
      - .:/app
    command: python Reportes/generador_reporte_lbs.py
